version: '2'
services:
    clockin-app:
        image: clockin
        external_links:
            - clockin-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/clockin?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 8181:8181
    clockin-mysql:
        extends:
            file: mysql.yml
            service: clockin-mysql
